http:
  port: ${NODE_PORT:-8080}
  hostname: 0.0.0.0
admin:
  port: ${ADMIN_PORT:-9876}
  hostname: 0.0.0.0
apiEndpoints:
  api:
    host: '*'
    paths: '/translate-docx'
  translate-docx:
    host: '*'
    paths: '/v2/translate-docx'
  fetch-languages:
    host: '*'
    paths: '/fetch-languages'
  fetch-models:
    host: '*'
    paths: '/fetch-models'
  fetch-process:
    host: '*'
    paths: '/fetch-translation-process'
  fetch-sentences:
    host: '*'
    paths: '/fetch-sentences'
  save-paragraph-workspace:
    host: '*'
    paths: '/save-paragraph-workspace'
  translation_en:
    host: '*'
    paths: '/translation_en'
  translation_hi:
    host: '*'
    paths: '/translation_hi'
  fetch-corpus-sentences:
    host: '*'
    paths: '/fetch-corpus-sentences'
  fetch-corpus:
    host: '*'
    paths: '/fetch-corpus'
  update-sentences:
    host: '*'
    paths: '/update-sentences'
  update-sentences-grade:
    host: '*'
    paths: '/update-sentences-grade'
  update-sentences-status:
    host: '*'
    paths: '/update-sentences-status'
  get-profile:
    host: '*'
    paths: '/get-profile'
  test-api:
    host: '*'
    paths: '/hello'
  update-password:
    host: '*'
    paths: '/update-password'
  upload-corpus:
    host: '*'
    paths: '/upload-corpus'
  translate:
    host: '*'
    paths: '/translate'
  fetch-benchmarks:
    host: '*'
    paths: '/fetch-benchmarks'
  fetch-benchmark-sentences:
    host: '*'
    paths: '/fetch-benchmark-sentences'
  fetch-benchmark-compare-sentences:
    host: '*'
    paths: '/fetch-benchmark-compare-sentences'
  fetch-benchmark-reports:
    host: '*'
    paths: '/fetch-benchmark-reports'
  fetch-benchmark-analyzer-reports:
    host: '*'
    paths: '/fetch-benchmark-analyzer-reports'
  get-corpus:
    host: '*'
    paths: '/get-corpus'
  translate-source:
    host: '*'
    paths: '/translate-source'
  list-users:
    host: '*'
    paths: '/list-users'
  list-roles:
    host: '*'
    paths: '/list-roles'
  create-user:
    host: '*'
    paths: '/create-user'
  update-user-status:
    host: '*'
    paths: '/update-user-status'
  save-benchmark:
    host: '*'
    paths: '/save-benchmark'
  update-password-admin:
    host: '*'
    paths: '/update-password-admin'
  fetch-paragraph-workspace:
    host: '*'
    paths: '/fetch-paragraph-workspace'
  start-tokenization:
    host: '*'
    paths: '/start-tokenization'
  fetch-paragraph-workspace-detail:
    host: '*'
    paths: '/fetch-paragraph-workspace-detail'
  translate-with-hemat:
    host: '*'
    paths: '/translate-with-hemat'
  fetch-default-config:
    host: '*'
    paths: '/fetch-default-config'
  download-docx:
    host: '*'
    paths: '/download-docx'
  save-translated-docx:
    host: '*'
    paths: '/save-translated-docx'
  save-mt-workspace:
    host: '*'
    paths: '/save-mt-workspace'
  fetch-mt-workspace:
    host: '*'
    paths: '/fetch-mt-workspace'
  fetch-mt-workspace-detail:
    host: '*'
    paths: '/fetch-mt-workspace-detail'
  fetch-high-courts:
    host: '*'
    paths: '/fetch-high-courts'
  update-high-court:
    host: '*'
    paths: '/update-high-court'
  save-high-court:
    host: '*'
    paths: '/save-high-court'
  migrate-old-data:
    host: '*'
    paths: '/migrate-old-data'
  translate-anuvaad:
    host: '*'
    paths: '/translate-anuvaad'
  save-search-replace-workspace:
    host: '*'
    paths: '/save-search-replace-workspace'
  fetch-search-replace-workspace:
    host: '*'
    paths: '/fetch-search-replace-workspace'
serviceEndpoints:
  httpbin:
    url: ${PYTHON_URL:-'http://gateway_python:5001/'}
  auto:
    url: ${AUTO_URL:-'http://documents.anuvaad.org/auto/'}
  corpusproxy:
    url: ${NODE_URL:-'http://documents.anuvaad.org/auto/anuvaad/v1/'}
  translation:
    url: ${NMT_URL:-'http://52.40.71.62:3003/translator/'}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - headers
pipelines:
  pipeline1:
    apiEndpoints:
      - test-api
      - download-docx
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - cors:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  admin:
    apiEndpoints:
      - list-users
      - list-roles
      - create-user
      - update-user-status
      - fetch-benchmark-reports
      - fetch-benchmark-analyzer-reports
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: corpusproxy 
              changeOrigin: true
  corpus:
    apiEndpoints:
      - fetch-corpus-sentences
      - save-paragraph-workspace
      - fetch-corpus
      - translate-source
      - update-sentences
      - update-sentences-status
      - update-sentences-grade
      - fetch-benchmarks
      - fetch-benchmark-sentences
      - fetch-benchmark-compare-sentences
      - list-users
      - list-roles
      - create-user
      - update-user-status
      - fetch-benchmark-reports
      - fetch-benchmark-analyzer-reports
      - translate-with-hemat
      - fetch-models
      - fetch-languages
      - fetch-paragraph-workspace
      - fetch-paragraph-workspace-detail
      - start-tokenization
      - fetch-default-config
      - save-mt-workspace
      - fetch-mt-workspace
      - fetch-mt-workspace-detail
      - fetch-high-courts
      - update-high-court
      - save-high-court
      - migrate-old-data
      - save-search-replace-workspace
      - fetch-search-replace-workspace
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: corpusproxy 
              changeOrigin: true
  translation:
    apiEndpoints:
      - translation_en
      - translation_hi
      - translate-anuvaad
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - rate-limit:
        - action:                         # allow
            max: 50                       # max 50 request
            delayMs: 0
            windowMs: 1000              # per 1 seconds
            rateLimitBy: "${consumer.token.authenticatedUserId}"
      - proxy:
          - action:
              serviceEndpoint: translation 
              changeOrigin: true
  auto:
    apiEndpoints:
      - translate
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - rate-limit:
        - action:                         # allow
            max: 50                       # max 50 request
            delayMs: 0
            windowMs: 1000              # per 1 seconds
            rateLimitBy: "${consumer.token.authenticatedUserId}"
      - proxy:
          - action:
              serviceEndpoint: auto 
              changeOrigin: true
  default:
    apiEndpoints:
      - api
      - translate-docx
      - fetch-process
      - fetch-sentences
      - get-profile
      - update-password
      - upload-corpus
      - get-corpus
      - update-password-admin
      - save-benchmark
      - save-translated-docx
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  
