http:
  port: ${NODE_PORT:-8080}
  hostname: 0.0.0.0
admin:
  port: ${ADMIN_PORT:-9876}
  hostname: 0.0.0.0
apiEndpoints:
  api:
    host: '*'
    paths: '/translate-docx'
  translate-docx:
    host: '*'
    paths: '/v2/translate-docx'
  fetch-languages:
    host: '*'
    paths: '/fetch-languages'
  fetch-models:
    host: '*'
    paths: '/fetch-models'
  fetch-process:
    host: '*'
    paths: '/fetch-translation-process'
  fetch-sentences:
    host: '*'
    paths: '/fetch-sentences'
  save-paragraph-workspace:
    host: '*'
    paths: '/save-paragraph-workspace'
  translation_en:
    host: '*'
    paths: '/translation_en'
  translation_hi:
    host: '*'
    paths: '/translation_hi'
  fetch-corpus-sentences:
    host: '*'
    paths: '/fetch-corpus-sentences'
  remove-process:
    host: '*'
    paths: '/remove-process'
  fetch-corpus:
    host: '*'
    paths: '/fetch-corpus'
  update-sentences:
    host: '*'
    paths: '/update-sentences'
  update-sentences-grade:
    host: '*'
    paths: '/update-sentences-grade'
  update-sentences-status:
    host: '*'
    paths: '/update-sentences-status'
  get-profile:
    host: '*'
    paths: '/get-profile'
  test-api:
    host: '*'
    paths: '/hello'
  update-password:
    host: '*'
    paths: '/update-password'
  upload-corpus:
    host: '*'
    paths: '/upload-corpus'
  translate:
    host: '*'
    paths: '/translate'
  fetch-benchmarks:
    host: '*'
    paths: '/fetch-benchmarks'
  fetch-benchmark-sentences:
    host: '*'
    paths: '/fetch-benchmark-sentences'
  fetch-benchmark-compare-sentences:
    host: '*'
    paths: '/fetch-benchmark-compare-sentences'
  fetch-benchmark-reports:
    host: '*'
    paths: '/fetch-benchmark-reports'
  fetch-benchmark-analyzer-reports:
    host: '*'
    paths: '/fetch-benchmark-analyzer-reports'
  get-corpus:
    host: '*'
    paths: '/get-corpus'
  translate-source:
    host: '*'
    paths: '/translate-source'
  list-users:
    host: '*'
    paths: '/list-users'
  list-roles:
    host: '*'
    paths: '/list-roles'
  create-user:
    host: '*'
    paths: '/create-user'
  update-user-status:
    host: '*'
    paths: '/update-user-status'
    scopes:
      - ['admin']
  save-benchmark:
    host: '*'
    paths: '/save-benchmark'
  update-password-admin:
    host: '*'
    paths: '/update-password-admin'
  fetch-paragraph-workspace:
    host: '*'
    paths: '/fetch-paragraph-workspace'
  start-tokenization:
    host: '*'
    paths: '/start-tokenization'
  fetch-paragraph-workspace-detail:
    host: '*'
    paths: '/fetch-paragraph-workspace-detail'
  translate-with-hemat:
    host: '*'
    paths: '/translate-with-hemat'
  fetch-default-config:
    host: '*'
    paths: '/fetch-default-config'
  download-docx:
    host: '*'
    paths: '/download-docx'
  save-composition-workspace:
    host: '*'
    paths: '/save-composition-workspace'
  save-translated-docx:
    host: '*'
    paths: '/save-translated-docx'
  save-mt-workspace:
    host: '*'
    paths: '/save-mt-workspace'
  fetch-mt-workspace:
    host: '*'
    paths: '/fetch-mt-workspace'
  fetch-mt-workspace-detail:
    host: '*'
    paths: '/fetch-mt-workspace-detail'
  fetch-high-courts:
    host: '*'
    paths: '/fetch-high-courts'
  update-high-court:
    host: '*'
    paths: '/update-high-court'
  save-high-court:
    host: '*'
    paths: '/save-high-court'
  migrate-old-data:
    host: '*'
    paths: '/migrate-old-data'
  translate-anuvaad:
    host: '*'
    paths: '/translate-anuvaad'
  save-search-replace-workspace:
    host: '*'
    paths: '/save-search-replace-workspace'
  fetch-search-replace-workspace:
    host: '*'
    paths: '/fetch-search-replace-workspace'
  fetch-search-replace-sentence:
    host: '*'
    paths: '/fetch-search-replace-sentence'
  update-search-replace-sentence:
    host: '*'
    paths: '/update-search-replace-sentence'
  fetch-search-replace-workspace-detail:
    host: '*'
    paths: '/fetch-search-replace-workspace-detail'
  save-mt-workspace-data:
    host: '*'
    paths: '/save-mt-workspace-data'
  save-paragraph-workspace-data:
    host: '*'
    paths: '/save-paragraph-workspace-data'
  fetch-feedback-questions:
    host: '*'
    paths: '/fetch-feedback-questions'
  save-feedback-questions:
    host: '*'
    paths: '/save-feedback-questions'
  check-feedback-pending:
    host: '*'
    paths: '/check-feedback-pending'
  save-captured-feedback:
    host: '*'
    paths: '/save-captured-feedback'
  accept-all-search-replace-sentence:
    host: '*'
    paths: '/accept-all-search-replace-sentence'
  fetch-composition-workspace:
    host: '*'
    paths: '/fetch-composition-workspace'
  fetch-composition-workspace-detail:
    host: '*'
    paths: '/fetch-composition-workspace-detail'
  start-pdf-parse-process:
    host: '*'
    paths: '/start-pdf-parse-process'
  fetch-pdf-parse-process:
    host: '*'
    paths: '/fetch-pdf-parse-process'
  fetch-pdf-sentences:
    host: '*'
    paths: '/fetch-pdf-sentences'
  extract-paragraphs:
    host: '*'
    paths: '/extract-paragraphs'
  extract-paragraphs-pagewise:
    host: '*'
    paths: '/extract-paragraphs-pagewise'
  tokenize-sentence:
    host: '*'
    paths: '/tokenize-sentence'
  tokenize-hindi-sentence:
    host: '*'
    paths: '/tokenize-hindi-sentence'
  interactive-translation:
    host: '*'
    paths: '/interactive-translation'
  convert-pdf-to-doc:
    host: '*'
    paths: '/convert-pdf-to-doc'
  lines:
    host: '*'
    paths: '/lines'
  extract:
    host: '*'
    paths: '/extract'
  ner:
    host: '*'
    paths: '/ner'
  translate-pdf:
    host: '*'
    paths: '/translate-pdf'
  update-pdf-sentences:
    host: '*'
    paths: '/update-pdf-sentences'
  make-doc-from-sentences:
    host: '*'
    paths: '/make-doc-from-sentences'
  extract-pdf-paragraphs:
    host: '*'
    paths: '/extract-pdf-paragraphs'
  extract-pdf-to-sentences:
    host: '*'
    paths: '/extract-pdf-to-sentences'
  merge-split-sentence:
    host: '*'
    paths: '/merge-split-sentence'
  aadhaar:
    host: '*'
    paths: '/aadhaar'
  ner_v0:
    host: '*'
    paths: '/v0/ner'
  feedback_report:
    host: '*'
    paths: '/feedback_report/_search'
    methods: ["GET", "OPTIONS"]
  doc_report:
    host: '*'
    paths: '/doc_report/_search'
    methods: ["GET", "OPTIONS"]
serviceEndpoints:
  httpbin:
    url: ${PYTHON_URL:-'http://gateway_python:5001/'}
  auto:
    url: ${AUTO_URL:-'http://documents.anuvaad.org/auto/'}
  corpusproxy:
    url: ${NODE_URL:-'http://documents.anuvaad.org/auto/anuvaad/v1/'}
  corpusproxywithoutauth:
    url: ${NODE_URL:-'http://documents.anuvaad.org/auto/anuvaad/v1/'}
  translation:
    url: ${NMT_URL:-'http://52.40.71.62:3003/translator/'}
  elastic:
    url: ${ELASTIC_URL:-'http://52.88.54.220:9200/'}
  interactive:
    url: ${INTERACTIVE_URL:-'http://52.40.71.62:5001/'}
  ocr_server:
    url: ${OCR_SERVER_URL:-'http://172.30.0.103:6000/api/v1/ocr/'}
  ocr_aadhar_server:
    url: 'http://172.30.0.103:5000/api/v1/ocr/'
  ner_server:
    url: 'http://172.30.0.103:5001/api/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - headers
  - jaeger-policy
pipelines:
  pipeline1:
    apiEndpoints:
      - test-api
      - download-docx
      - tokenize-sentence
      - tokenize-hindi-sentence
      - ner
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - cors:
      - jaeger-policy:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  admin:
    apiEndpoints:
      - list-users
      - list-roles
      - create-user
      - update-user-status
      - fetch-benchmark-reports
      - fetch-benchmark-analyzer-reports
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: corpusproxy 
              changeOrigin: true
  corpus:
    apiEndpoints:
      - fetch-corpus-sentences
      - save-paragraph-workspace
      - fetch-corpus
      - translate-source
      - update-sentences
      - update-sentences-status
      - update-sentences-grade
      - fetch-benchmarks
      - fetch-benchmark-sentences
      - fetch-benchmark-compare-sentences
      - list-users
      - list-roles
      - translate-with-hemat
      - fetch-models
      - fetch-languages
      - fetch-paragraph-workspace
      - fetch-paragraph-workspace-detail
      - start-tokenization
      - fetch-default-config
      - save-mt-workspace
      - fetch-mt-workspace
      - fetch-mt-workspace-detail
      - fetch-high-courts
      - update-high-court
      - save-high-court
      - migrate-old-data
      - save-search-replace-workspace
      - fetch-search-replace-workspace
      - fetch-search-replace-sentence
      - update-search-replace-sentence
      - fetch-search-replace-workspace-detail
      - save-mt-workspace-data
      - save-paragraph-workspace-data
      - save-feedback-questions
      - fetch-feedback-questions
      - check-feedback-pending
      - save-captured-feedback
      - accept-all-search-replace-sentence
      - save-composition-workspace
      - fetch-composition-workspace
      - fetch-composition-workspace-detail
      - start-pdf-parse-process
      - fetch-pdf-parse-process
      - fetch-pdf-sentences
      - convert-pdf-to-doc
      - translate-pdf
      - update-pdf-sentences
      - make-doc-from-sentences
      - extract-pdf-paragraphs
      - extract-pdf-to-sentences
      - merge-split-sentence
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: corpusproxy 
              changeOrigin: true
  elasticsearch:
    apiEndpoints:
      - doc_report
      - feedback_report
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - cors:
         - action:
              origin: true
              methods: 'GET'
              maxAge: 100000000
      - proxy:
          - action:
              serviceEndpoint: elastic 
              changeOrigin: true
  translation:
    apiEndpoints:
      - translation_en
      - translation_hi
      - translate-anuvaad
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - rate-limit:
        - action:                         # allow
            max: 50                       # max 50 request
            delayMs: 0
            windowMs: 1000              # per 1 seconds
            rateLimitBy: "${consumer.token.authenticatedUserId}"
      - proxy:
          - action:
              serviceEndpoint: translation 
              changeOrigin: true
  interactive:
    apiEndpoints:
      - interactive-translation
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - rate-limit:
        - action:                         # allow
            max: 50                       # max 50 request
            delayMs: 0
            windowMs: 1000              # per 1 seconds
            rateLimitBy: "${consumer.token.authenticatedUserId}"
      - proxy:
          - action:
              serviceEndpoint: interactive 
              changeOrigin: true
  ocr:
    apiEndpoints:
      - lines
      - extract
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - proxy:
          - action:
              serviceEndpoint: ocr_server 
              changeOrigin: true
  ocr_aadhar:
    apiEndpoints:
      - aadhaar
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - proxy:
          - action:
              serviceEndpoint: ocr_aadhar_server 
              changeOrigin: true
  ner_server_proxy:
    apiEndpoints:
      - ner_v0
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - proxy:
          - action:
              serviceEndpoint: ner_server 
              changeOrigin: true
  corpusproxywithoutauth:
    apiEndpoints:
      - extract-paragraphs
      - extract-paragraphs-pagewise
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: corpusproxywithoutauth 
              changeOrigin: true
  auto:
    apiEndpoints:
      - translate
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - rate-limit:
        - action:                         # allow
            max: 50                       # max 50 request
            delayMs: 0
            windowMs: 1000              # per 1 seconds
            rateLimitBy: "${consumer.token.authenticatedUserId}"
      - proxy:
          - action:
              serviceEndpoint: auto 
              changeOrigin: true
  default:
    apiEndpoints:
      - api
      - translate-docx
      - fetch-process
      - fetch-sentences
      - get-profile
      - update-password
      - upload-corpus
      - get-corpus
      - update-password-admin
      - save-benchmark
      - save-translated-docx
      - remove-process
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jaeger-policy:
      - cors:
         - action:
              origin: true
              methods: 'GET,PUT,PATCH,POST,DELETE,HEAD'
              maxAge: 100000000
      - oauth2:
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true


              