http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: '*'
    paths: '/translate-docx'
serviceEndpoints:
  httpbin:
    url: 'http://localhost:5001/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - headers
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - oauth2:
         - action:
            passThrough: true
      - headers:
         - action:
              headersPrefix: 'ad-'
              forwardHeaders:
                userid: 'consumer.token.authenticatedUserId'
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
              
