# Core
db:
  redis:
    host: ${REDIS_URL:-localhost}
    port: ${REDIS_PORT:-6379}
    namespace: AG

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config'

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  storeProvider: connect-redis
  storeOptions:
    host: ${REDIS_URL:-localhost}
    port: ${REDIS_PORT:-6379}
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 720000000
refreshTokens:
  timeToExpiry: 720000000
authorizationCodes:
  timeToExpiry: 720000000

plugins:
  rewrite:
    package: express-gateway-plugin-rewrite
